default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: rater
  password: hg4b0vzytp
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: book_review_app_development

test:
  <<: *default
  database: book_review_app_test


production:
  <<: *default
  database: book_review_app_production
  username: book_review_app
  password: <%= ENV['BOOK_REVIEW_APP_DATABASE_PASSWORD'] %>
